export const EVENT_TYPES = [
  "BusinessCreated",
  "BusinessPublished",
  "BusinessUpdated",
  "BusinessSuspended",
  "BusinessDeleted",
  "BusinessTypeAssigned",
  "ClaimRequestSubmitted",
  "ClaimApproved",
  "ClaimRejected",
  "VerificationStarted",
  "VerificationUpdated",
  "VerificationExpired",
  "BusinessScoreRecalculated",
  "ProductCreated",
  "ProductUpdated",
  "ProductDeleted",
  "ServiceCreated",
  "ServiceUpdated",
  "ServiceDeleted",
  "PortfolioPublished",
  "PortfolioDeleted",
  "UpdatePublished",
  "UpdateDeleted",
  "MediaUploaded",
  "MediaDeleted",
  "ReviewSubmitted",
  "ReviewModerated",
  "FeedbackSubmitted",
  "EngagementEventFired",
  "SavedItemAdded",
  "SavedItemRemoved",
  "UserRegistered",
  "UserEmailVerified",
  "UserPasswordChanged",
  "UserSuspended",
  "NotificationCreated",
  "BusinessRoleGranted",
  "BusinessRoleRevoked",
] as const;

export type EventType = (typeof EVENT_TYPES)[number];
